let pre = "Écrivez ici...";
let pro = [
    ["I","Je"],
    ["You","Tu"],
    ["He / She","Il / Elle"],
    ["We","Nous"],
    ["You pl.","Vous"],
    ["They / fem.","Ils / Elles"],
];
let pres  = [
    [["ate","Manger"],["mangeai","mangeas","mangea","mangeâmes","mangeâtes","mangèrent"]],
    [["spoke","Parler"],["parlai","parlas","parla","parlâmes","parlâtes","parlèrent"]],
    [["finished","Finir"],["finis","finis","finit","finîmes","finîtes","finirent"]],
    [["took","Prendre"],["pris","pris","prit","prîmes","prîtes","prirent"]],
    [["went","Aller"],["allai","allas","alla","allâmes","allâtes","allèrent"]],
    [["was/were","Être"],["fus","fus","fut","fûmes","fûtes","furent"]],
    [["had","Avoir"],["eus","eus","eut","eûmes","eûtes","eurent"]],
    [["did","Faire"],["fis","fis","fit","fîmes","fîtes","firent"]],
    [["said","Dire"],["dis","dis","dit","dîmes","dîtes","dirent"]],
    [["came","Venir"],["vins","vins","vint","vînmes","vîntes","vinrent"]],
    [["could","Pouvoir"],["pus","pus","put","pûmes","pûtes","purent"]],
    [["wanted","Vouloir"],["voulus","voulus","voulut","voulûmes","voulûtes","voulurent"]],
    [["knew (a fact)","Savoir"],["sus","sus","sut","sûmes","sûtes","surent"]],
    [["saw","Voir"],["vis","vis","vit","vîmes","vîtes","virent"]],
    [["drank","Boire"],["bus","bus","but","bûmes","bûtes","burent"]],
    [["wrote","Écrire"],["écrivis","écrivis","écrivit","écrivîmes","écrivîtes","écrivirent"]],
    [["put/place","Mettre"],["mis","mis","mit","mîmes","mîtes","mirent"]],
    [["believed","Croire"],["crus","crus","crut","crûmes","crûtes","crurent"]],
    [["read","Lire"],["lus","lus","lut","lûmes","lûtes","lurent"]],
    [["sent","Envoyer"],["envoyai","envoyas","envoya","envoyâmes","envoyâtes","envoyèrent"]],
    [["opened","Ouvrir"],["ouvris","ouvris","ouvrit","ouvrîmes","ouvrîtes","ouvrirent"]],
    [["ran","Courir"],["courus","courus","courut","courûmes","courûtes","coururent"]],
    [["became","Devenir"],["devins","devins","devint","devînmes","devîntes","devinrent"]],
    [["held","Tenir"],["tins","tins","tint","tînmes","tîntes","tinrent"]],
    [["lived","Vivre"],["vécus","vécus","vécut","vécûmes","vécûtes","vécurent"]],
    [["heard","Entendre"],["entendis","entendis","entendit","entendîmes","entendîtes","entendirent"]],
    [["lost","Perdre"],["perdis","perdis","perdit","perdîmes","perdîtes","perdirent"]],
    [["answered","Répondre"],["répondis","répondis","répondit","répondîmes","répondîtes","répondirent"]],
    [["fell","Tomber"],["tombai","tombas","tomba","tombâmes","tombâtes","tombèrent"]],
    [["worked","Travailler"],["travaillai","travaillas","travailla","travaillâmes","travaillâtes","travaillèrent"]],
    [["paid","Payer"],["payai","payas","paya","payâmes","payâtes","payèrent"]],
    [["won","Gagner"],["gagnai","gagnas","gagna","gagnâmes","gagnâtes","gagnèrent"]],
    [["changed","Changer"],["changeai","changeas","changea","changeâmes","changeâtes","changèrent"]],
    [["called","Appeler"],["appelai","appelas","appela","appelâmes","appelâtes","appelèrent"]],
    [["worked","Marcher"],["marchai","marchas","marcha","marchâmes","marchâtes","marchèrent"]],
    [["belonged","Appartenir"],["appartins","appartins","appartint","appartînmes","appartîntes","appartinrent"]],
    [["sat","S’asseoir"],["assis","assis","assit","assîmes","assîtes","assirent"]],
    [["died","Mourir"],["mourus","mourus","mourut","mourûmes","mourûtes","moururent"]],
    [["opened","Découvrir"],["découvris","découvris","découvrit","découvrîmes","découvrîtes","découvrirent"]],
    [["escaped","S’échapper"],["m’échappai","m’échappas","m’échappa","m’échappâmes","m’échappâtes","m’échappèrent"]],
    [["sent","Transmettre"],["transmis","transmis","transmit","transmîmes","transmîtes","transmirent"]],
    [["killed","Tuer"],["tueai","tueas","tuea","tueâmes","tueâtes","tuèrent"]],
    [["cut","Couper"],["coupai","coupas","coupa","coupâmes","coupâtes","coupèrent"]],
    [["sang","Chanter"],["chantai","chantas","chanta","chantâmes","chantâtes","chantèrent"]],
    [["loved","Aimer"],["aimai","aimas","aima","aimâmes","aimâtes","aimèrent"]],
    [["helped","Aider"],["aidai","aidas","aida","aidâmes","aidâtes","aidèrent"]],
    [["studied","Étudier"],["étudiai","étudias","étudia","étudiâmes","étudiâtes","étudièrent"]],
    [["tried","Essayer"],["essayai","essayas","essaya","essayâmes","essayâtes","essayèrent"]],
    [["waited","Attendre"],["attendis","attendis","attendit","attendîmes","attendîtes","attendirent"]]
  ];