let pre = "Écrivez ici...";
let pro = [
    ["I","Je"],
    ["You","Tu"],
    ["He / She","Il / Elle"],
    ["We","Nous"],
    ["You pl.","Vous"],
    ["They / fem.","Ils / Elles"],
];
let pres = [
    [["be","Être"],["sois","sois","soit","soyons","soyez","soient"]],
    [["have","Avoir"],["aie","aies","ait","ayons","ayez","aient"]],
    [["go","Aller"],["aille","ailles","aille","allions","alliez","aillent"]],
    [["do","Faire"],["fasse","fasses","fasse","fassions","fassiez","fassent"]],
    [["can","Pouvoir"],["puisse","puisses","puisse","puissions","puissiez","puissent"]],
    [["want","Vouloir"],["veuille","veuilles","veuille","voulions","vouliez","veuillent"]],
    [["know (fact)","Savoir"],["sache","saches","sache","sachions","sachiez","sachent"]],
    [["take","Prendre"],["prenne","prennes","prenne","prenions","preniez","prennent"]],
    [["come","Venir"],["vienne","viennes","vienne","venions","veniez","viennent"]],
    [["see","Voir"],["voie","voies","voie","voyions","voyiez","voient"]],
    [["believe","Croire"],["croie","croies","croie","croyions","croyiez","croient"]],
    [["must","Falloir"],["faille","faille","faille","fallions","falliez","faillent"]],
    [["rain","Pleuvoir"],["pleuve","pleuve","pleuve","pleuvions","pleuviez","pleuvent"]],
    [["die","Mourir"],["meure","meures","meure","mourions","mouriez","meurent"]],
    [["hold","Tenir"],["tienne","tiennes","tienne","tenions","teniez","tiennent"]],
    [["speak","Parler"],["parle","parles","parle","parlions","parliez","parlent"]],
    [["finish","Finir"],["finisse","finisses","finisse","finissions","finissiez","finissent"]],
    [["sell","Vendre"],["vende","vendes","vende","vendions","vendiez","vendent"]],
    [["wait","Attendre"],["attende","attendes","attende","attendions","attendiez","attendent"]],
    [["choose","Choisir"],["choisisse","choisisses","choisisse","choisissions","choisissiez","choisissent"]],
    [["build","Construire"],["construise","construises","construise","construisions","construisiez","construisent"]],
    [["read","Lire"],["lise","lises","lise","lisions","lisiez","lisent"]],
    [["write","Écrire"],["écrive","écrives","écrive","écrivions","écriviez","écrivent"]],
    [["open","Ouvrir"],["ouvre","ouvres","ouvre","ouvrions","ouvriez","ouvrent"]],
    [["sleep","Dormir"],["dorme","dormes","dorme","dormions","dormiez","dorment"]],
    [["say","Dire"],["dise","dises","dise","disions","disiez","disent"]],
    [["run","Courir"],["coures","coures","coure","courions","couriez","courent"]],
    [["give","Donner"],["donne","donnes","donne","donnions","donniez","donnent"]],
    [["help","Aider"],["aide","aides","aide","aidions","aidiez","aident"]],
    [["start","Commencer"],["commence","commences","commence","commencions","commenciez","commencent"]],
    [["eat","Manger"],["mange","manges","mange","mangions","mangiez","mangent"]],
    [["study","Étudier"],["étudie","étudies","étudie","étudiions","étudiiez","étudient"]],
    [["watch","Regarder"],["regarde","regardes","regarde","regardions","regardiez","regardent"]],
    [["live","Habiter"],["habite","habites","habite","habitions","habitiez","habitent"]],
    [["play","Jouer"],["joue","joues","joue","jouions","jouiez","jouent"]]
];